package domain

import "errors"

var (
	ErrNotFound                   = errors.New("WBS was not found")
	ErrParentNotFound             = errors.New("parent WBS was not found")
	ErrProjectNotFound            = errors.New("project was not found")
	ErrNameRequired               = errors.New("WBS name is required")
	ErrNameTooLong                = errors.New("WBS name must be 200 characters or fewer")
	ErrNameExists                 = errors.New("a sibling WBS with this name already exists")
	ErrHasChildren                = errors.New("move or delete this WBS's children first")
	ErrCycle                      = errors.New("WBS cannot be moved under itself or its descendant")
	ErrProjectMismatch            = errors.New("WBS parent must belong to the same project")
	ErrConversionRequired         = errors.New("confirm moving executable data to the first child")
	ErrExecutableOnly             = errors.New("executable fields are available only on a leaf WBS")
	ErrManualTimeline             = errors.New("manual timeline is available only for an open project with automatic scheduling off")
	ErrTimelinePair               = errors.New("timeline start and end must both be provided")
	ErrTimelineOrder              = errors.New("timeline end must be on or after start")
	ErrActualDatePair             = errors.New("actual start and actual end must both be provided")
	ErrActualDateOrder            = errors.New("actual end must be on or after actual start")
	ErrIncompletePredecessor      = errors.New("all predecessors must be completed before this task can be completed")
	ErrEffortInvalid              = errors.New("effort must be at least 0.5 hours in 0.5 hour increments")
	ErrLagInvalid                 = errors.New("lag must be a non-negative whole number of days")
	ErrCapacityAllocationInvalid  = errors.New("capacity allocation percentage must be a whole number from 1 to 100")
	ErrRoleAssigneeMismatch       = errors.New("assignee role does not match the selected role")
	ErrCompletedReadOnly          = errors.New("completed executable WBS is read-only")
	ErrTaskNotCompleted           = errors.New("task is not completed")
	ErrTaskReopenConflict         = errors.New("task reopen conflicted with another state transition")
	ErrProjectClosedReadOnly      = errors.New("closed project is read-only")
	ErrProjectLockedReadOnly      = errors.New("locked project planning is read-only")
	ErrSchedulePreviewIncomplete  = errors.New("role, effort, and valid lag are required for schedule preview")
	ErrSchedulePreviewUnavailable = errors.New("automatic schedule preview is available only for an open unfinished Task with Automatic Scheduling on")
	ErrMoveNotAllowed             = errors.New("WBS cannot move further in that direction")
)
